### ISSUE TITLE
Add OTA

### ISSUE THREAD

**Issue by xmdnx** [rabbitgramdesktop/rabbitgramdesktopold#23]
### Is your feature request related to a problem?

No

### Describe the solution you'd like

add stock telegram OTA for КРОЛИКГРАМ

### Describe alternatives you've considered

no one

**Comment by cherryymerryy** [comment]
add stock telegram OTA for rabbitGram*

**Comment by spira007** [comment]
КРОЛИКГРАМ

**Comment by xmdnx** [comment]
> add stock telegram OTA for rabbitGram*
> 

there's no stock Telegram OTA available in sources

**Comment by spira007** [comment]
doesn't ЭКСТЕРАМАГР have OTA? psate it from there!

**Comment by xmdnx** [comment]
> doesn't ЭКСТЕРАМАГР have OTA? paste it from there!

how are you going to use ota of android client on desktop

**Comment by spira007** [comment]
> > doesn't ЭКСТЕРАМАГР have OTA? paste it from there!
> 
> how are you going to use ota of android client on desktop

i am fucking retarded im sorry, i forgor its a desktop app.

**Comment by xmdnx** [comment]
@spira007 ota very soon btw
